# Generated by Django 3.2.16 on 2023-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_author_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='это заголовок класс'),
            preserve_default=False,
        ),
    ]
